### ISSUE TITLE
Automatic Logon: "User Experience"

### ISSUE THREAD

**Issue by g-back** [fidley/ABAP-Project-Extensions#2]
first: thanks for the plugin!

just a few ideas:
1. automatically prompt for password when a new ABAP project is added, add setting to enable/disable this prompt
   - similar behaviour exists in addon "ABAP CI" for colouring the projects
2. when you use "Logon with Secure storage" on a project without a saved password, nothing happens. Add a message that tells you that no password has been saved for this project?
3. possibility to enable/disable automatic logon for each project
   - Use case: you want to save the password, but don't necessarily want to automatically logon automatically

**Comment by fidley** [comment]
After deselecting the option Logon Automatically for all stored users, the automatic logon will start only for projects/clients/users selected on the Passwords view.
![image](https://user-images.githubusercontent.com/7912195/76580463-55949f00-64d0-11ea-9088-0ef8d67841b0.png)

![image](https://user-images.githubusercontent.com/7912195/76580481-6513e800-64d0-11ea-84df-5aa47a2b677d.png)
